// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Burrow) DeepCopyInto(out *Burrow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Burrow.
func (in *Burrow) DeepCopy() *Burrow {
	if in == nil {
		return nil
	}
	out := new(Burrow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Burrow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurrowConfigSpec) DeepCopyInto(out *BurrowConfigSpec) {
	*out = *in
	out.Logging = in.Logging
	out.Zookeeper = in.Zookeeper
	out.ClientProfileKafkaProfile = in.ClientProfileKafkaProfile
	out.ClusterMyCluster = in.ClusterMyCluster
	out.ConsumerConsumerKafka = in.ConsumerConsumerKafka
	out.HttpserverDefault = in.HttpserverDefault
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurrowConfigSpec.
func (in *BurrowConfigSpec) DeepCopy() *BurrowConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BurrowConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurrowList) DeepCopyInto(out *BurrowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Burrow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurrowList.
func (in *BurrowList) DeepCopy() *BurrowList {
	if in == nil {
		return nil
	}
	out := new(BurrowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BurrowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurrowStatus) DeepCopyInto(out *BurrowStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurrowStatus.
func (in *BurrowStatus) DeepCopy() *BurrowStatus {
	if in == nil {
		return nil
	}
	out := new(BurrowStatus)
	in.DeepCopyInto(out)
	return out
}
