apiVersion: v1
kind: Secret
metadata:
  name: subravi-robot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJjb250YWluZXJzLmNpc2NvLmNvbSI6IHsKICAgICAgImF1dGgiOiAiYzNWaWNtRjJhU3R5YjJKdmREcFRSVUpIUWpGTk5FUk1PRlZXV2tRMlJEWTBNVm95UjBWTlV6QXhVMDVGVURCS1VVMUlVVkpJUXpreFZVaEhXbEJOVWtkWlRrRXlVMGRVV1ZWRVIwazEiLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
