apiVersion: monitors.aims.cisco.com/v1beta1
kind: Burrow
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: burrow-sample
spec:
  apiport: 8080
  metricsport: 8000
  burrowImag: "containers.cisco.com/jaganaga/burrow:1.0"
  exporterImage: "containers.cisco.com/jaganaga/burrow-exporter:1.0"
  zookeeper:
    zkservers: "my-cluster-zookeeper-0.my-cluster-zookeeper-nodes:21810,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes:21811,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes:21812"
  consumer:
    bkservers: "my-cluster-kafka-bootstrap:9092"
  client-profile:
    kafka-version: "2.0.1"
  interval: 15
  api_version: 3
